### PR TITLE
Add example of parsing ordered and unordered lists

### PR DESCRIPTION
**Pull request by nigelhanlon**
Clubhouse card: https://app.clubhouse.io/condenastinternational/story/7845/add-list-to-example-implementation

### CODE REVIEW

**Comment by srilq** [comment]
The markdown output in CI looks a bit weird to me with the XML indented (the inline tags especially). I don’t think source XML will be formatted like that so maybe we shouldn’t do that in the example.

**Comment by srilq** [comment]
(P.S. I’m just on my phone, didn’t see it was merged already.)

**Comment by srilq** [comment]
CI link for clarity:
https://travis-ci.org/conde-nast-international/copilot-markdown-generator-php/jobs/330895976#L565

**Comment by nigelhanlon** [comment]
@srilq I didn't believe formatting the XML would have any impact as we parse the tags not the newlines etc. I was trying to make it more readable when looking at the example, but I can of course submit a new PR without the formatting if you like?

**Comment by srilq** [comment]
@nigelhanlon Newlines and indentation need to be preserved in the generator `$text` input because the input is Markdown format — that’s how nested tags work. So any newlines and whitespace will be preserved as it is in the input.

If the XML needs to contain newlines and indentation (or any other white space that is arbitrary from the PoV of the library), the implementing content converter needs to account for that by stripping it beforehand (or after-the-fact). Personally, it seems easier to me to just provide the XML in an in-line format. I imagine it will be like that in a real scenario (as it is in eZ XML), but this does raise the question of how we expect a content converter to work for XML that is stored in a human-readable tree like this. I don’t see a universal solution, but I also feel like this would need to be handled by the converter, not the library.

Does this make sense?

**Pull request merged**
